# Uncomment the next line to define a global platform for your project

platform :ios, '11.0'

target 'CarShare' do
    pod 'SnapKit'
    pod 'Moya'
    pod 'SwiftyJSON'
    pod 'HandyJSON'
    pod 'GearRefreshControl'
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'MJRefresh'
    #消息提示
    pod 'SwiftMessages'
    #pod 'YYKit'
    pod 'SVProgressHUD'
end
